name: Publish branch name to tag
on:
  push:
    branches:
      - stable
      - beta
      - canary 
      - rc
      # todo: remove test branch
      - TMEDIA-569-publish-tags 

jobs: 
  publish:
    name: Publish based on named branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # extract branch name
      - name: Extract branch name
        shell: bash
        run: echo "echo ${GITHUB_REF#refs/heads/}"

      # Prerelease
      - run: npm version prerelease --preid=${GITHUB_REF#refs/heads/}

      # Publish
      - run: npm publish --tag ${GITHUB_REF#refs/heads/}

      # Push tag
      - run: git push origin ${GITHUB_REF#refs/heads/} -f