name: Publish branch name to tag
on:
  push:
    branches:
      - stable
      - beta
      - canary 
      - rc
      # todo: remove test branch
      - TMEDIA-569-publish-tags 

jobs: 
  publish:
    name: Checkout the repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # extract branch name
      - name: Extract branch name
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      # extract branch name on pull request
      - name: Print branch name
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"

      # print branch name
      - name: Get branch name
        run: echo 'The branch name is' $BRANCH_NAME  

      # Prerelease
      # - run: npm version prerelease --preid=$BRANCH_NAME

      # # Publish
      # - run: npm publish --tag $BRANCH_NAME

      # # Push tag
      # - run: git push origin $BRANCH_NAME -f