name: Publish branch name to tag
on: push
  branches: 
    - stable
    - beta
    - canary 
    - rc
    # todo: remove test branch
    - TMEDIA-569-publish-tags 

jobs: 
  checkout: 
      - name: Checkout repo
        uses: actions/checkout@v2
